# Generated by Django 2.2 on 2020-12-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('User_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('User_Name', models.CharField(max_length=64, verbose_name='用户昵称')),
                ('User_Tel', models.CharField(max_length=16, verbose_name='联系方式')),
                ('User_Ordered_Car_id', models.ManyToManyField(to='login.CarInfo')),
            ],
        ),
    ]
