# Generated by Django 2.2 on 2020-12-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_carinfo_car_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='Car_IsUse',
            field=models.BooleanField(default=False, verbose_name='车辆是否在使用'),
        ),
    ]
