# Generated by Django 2.2 on 2020-12-25 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_carinfo_car_isuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='User_Register_Time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='账户注册时间'),
            preserve_default=False,
        ),
    ]
