# Generated by Django 2.2 on 2020-12-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userinfo_user_register_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='User_Identity',
            field=models.CharField(default='管理员', max_length=16, verbose_name='用户身份'),
        ),
    ]
