# Generated by Django 2.2 on 2020-12-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_userinfo_user_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='User_Identity',
            field=models.CharField(max_length=16, verbose_name='用户身份'),
        ),
    ]
