# Generated by Django 2.2 on 2020-12-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20201226_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='Car_Current_PosX',
            field=models.DecimalField(decimal_places=6, default=116.354826, max_digits=10, verbose_name='汽车当前位置经度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carinfo',
            name='Car_Current_PosY',
            field=models.DecimalField(decimal_places=6, default=40.003975, max_digits=10, verbose_name='汽车当前位置纬度'),
            preserve_default=False,
        ),
    ]
