# Generated by Django 2.2 on 2020-12-29 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20201226_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='UserAccount',
            field=models.CharField(default='root', max_length=16, verbose_name='用户账号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='UserPwd',
            field=models.CharField(default='123456', max_length=16, verbose_name='用户密码'),
            preserve_default=False,
        ),
    ]
