# Generated by Django 2.2 on 2020-12-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20201229_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='UserAccount',
            field=models.CharField(default='root', max_length=16, verbose_name='用户账号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='UserPwd',
            field=models.CharField(default='123456', max_length=16, verbose_name='用户密码'),
        ),
    ]
